# Generated by Django 5.0.6 on 2024-11-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage_mate', '0005_destination_country_alter_connector_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='destination',
            field=models.TextField(),
        ),
    ]
